name: mobile
description: "KOLPON"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.2.6+3

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0
  phone_state: ^2.1.1
  flutter_background_service: ^5.1.0
  call_e_log: ^0.0.4
  event_bus: ^2.0.1
  provider: ^6.1.2
  graphql_flutter: ^5.1.2
  flutter_local_notifications: ^18.0.1
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  intl: ^0.20.2
  path: ^1.9.1
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.5
  http: ^1.3.0
  app_installer: ^1.3.1
  shared_preferences: ^2.5.3
  build_runner: ^2.4.15
  hive_ce: ^2.10.1
  hive_ce_flutter: ^2.2.0
  hive_ce_generator: ^1.8.2
  dio: ^5.8.0+1
  gql_dio_link: ^1.0.1+1
  flutter_broadcasts_4m: ^0.4.2
  proximity_sensor: ^1.3.8
  url_launcher: ^6.3.1
  get_it: ^8.0.3
  marquee: ^2.3.0
  flutter_windowmanager_plus: ^1.0.1
  fluttertoast: ^8.2.12
  device_info_plus: ^11.5.0
  restart_app: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg