name: mobile
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_storage: ^2.1.1
  permission_handler: ^11.4.0
  phone_state: ^2.1.1
  flutter_background_service: ^5.1.0
  call_e_log: ^0.0.4
  flutter_sms_intellect: ^0.0.2
  event_bus: ^2.0.1
  flutter_slidable: ^4.0.0
  provider: ^6.1.2
  graphql_flutter: ^5.1.2
  connectivity_plus: ^6.1.3
  flutter_contacts: ^1.1.9+2
  flutter_local_notifications: ^18.0.1
  flutter_quill: ^11.0.0
  flutter_quill_extensions: ^11.0.0
  intl: ^0.19.0
  path: ^1.9.1
  flutter_localizations:
    sdk: flutter
  flutter_overlay_window: ^0.4.5
  app_installer: ^1.3.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - icons/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg